version: '3.3'

services:
  nlw-heat-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn start
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - nlw-heat-database
  
  nlw-heat-database:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
